version: '3.8'

services:
  # --- Continuous Backup Service ---
  backup:
    image: registry.gitlab.notyouraverage.dev/a.anand.91119/vaultwarden-backup:latest
    container_name: vaultwarden-backup
    restart: unless-stopped
    environment:
      # Optional: Enable verbose script logging (defaults to false)
      - VERBOSE_LOGGING=false
      # Optional: Set container timezone
      - TZ=Asia/Kolkata
    volumes:
      # !!! Mount host Docker socket (required for stop/start) !!!
      - /var/run/docker.sock:/var/run/docker.sock
      
      # Mount configuration file (read-only)
      # Source (Left side): Path to your config.yaml on the HOST
      # Target (Right side): Path inside the container where the script looks for config
      - ./config.yaml:/config/config.yaml:ro
      
      # Mount host Vaultwarden data directory (read-only for backup)
      # Source (Left side): ACTUAL path to Vaultwarden data on the HOST
      # Target (Right side): Path inside the container - THIS MUST MATCH 'vaultwarden.data_dir' in config.yaml
      # !!! Replace left side with your actual host path !!!
      - /path/to/vaultwarden/host/data-directory:/data:ro
      
      # Mount host backup storage directory
      # Source (Left side): ACTUAL path to backup storage on the HOST
      # Target (Right side): Path inside the container - THIS MUST MATCH 'backup.destination.path' in config.yaml
      # !!! Replace left side with your actual host path !!!
      - /path/to/your/backup/storage:/backup
